### ISSUE TITLE
Fix Search* tests 404 vs empty list behavior

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#87] opened 2015-09-17 22:46 UTC
Issues that I've found:
- ReadGroupSetsSearchIT.readGroupSetsNonexistentNameShouldSayNotFound
  - Should expect an empty list
- ReadGroupSetsGetByNameIT.testSearchForBogusNameFails (this appears to test duplicate functionality at the above test?)
  - Should expect an empty list
- ReadGroupSetsSearchIT.readgroupSetResponseForNonexistentDatasetIdShouldReturnEmptyList()
  - Should expect a 404, since the dataset does not exist. This is not freeform criteria - this is a container object.

Some of these points perhaps should be clarified in the spec, but the compliance test is either being more specific than the spec, or is in conflict with the spec on this point.

**Comment by jeromekelleher** [comment] 2015-09-18 09:18
Agreed with @calbach on these examples.

**Comment by hjellinek** [comment] 2015-09-21 18:57
The spec is unfortunately silent on this, and the current behavior is based on my (possible mis-)interpretation of an earlier email discussion of this topic.

I'm happy to test for either behavior, but until the spec codifies this, we run the risk of having any fix done now magically turn into a regression later.

As such, I will assign myself the task of updating the schema docs (since this will include HTTP status code, which are external to the schemas, maybe "API docs" is more correct).  The doc updates should get checked in first; the updated tests can follow.

**Closed** 2015-09-22 16:53 UTC
