### ISSUE TITLE
compliance_redux: questions/suggestions for test data

### ISSUE THREAD

**Issue by dglazer** [ga4gh/compliance#34] opened 2015-08-13 21:28 UTC
**Main Questions**

* 1) For the 5 BAM files in the reads folders, am I right to assume that there should be exactly one readgroupset per file?
* 2) The supplied references don't match the reads -- is that intentional?
* 3) For references, instead of requiring a custom set of references, I suggest instead requiring one of the known (and checksummed) standard referencesets. Any practical implementation will need that anyway. (I don't mind also having custom references in the tests, but it seems much lower priority.)

**Minor Data Comments**

* 4) How do we decide how much test data it's important to have, and what extra value we get from having more? For example, how much better are the tests because we have these five BAMs instead of just one or two, and these ten VCFs instead of just one or two? (Not a problem to have more, but I want to make sure we're being thoughtful about when to have more files and what each new one adds.)
* 5) It would be nice if it were easy to download *just* the compliance data, without also getting all of the code (not a big deal, since the code’s not big today, but a bit of a nuisance).
* 6) For import into the Google server, it would be a tiny bit more convenient if the BAMs and VCFs were 'flatter', instead of being spread across multiple folders. If nothing else, can we avoid having duplicate filenames in different directories (like currently happens with the VCFs)?

**Comment by diekhans** [comment] 2015-08-13 21:47
David Glazer <notifications@github.com> writes:
>   • 2) The supplied references don't match the reads -- is that intentional?

That sounds like a development timing issue, we should address
that to allow for tests reads+reference use cases.  This
probably means modifying the reads to match a custom reference
set.  We can do this my build the reference set from parts of
the genome, picking reads that map there and then remapping
them.

>   • 3) For references, instead of requiring a custom set of references, I
>     suggest instead requiring one of the known (and checksummed) standard
>     referencesets.

We need to be able to test corner cases in the reference API,
hence the need to be able to have custom reference sets.

>     Any practical implementation will need that anyway. (I don't
>     mind also having custom references in the tests, but it seems much lower
>     priority.)

A server that serves model organism data might not have a human
reference.  It's really important to have self-contain and
self-consistent test data to make it reliable and straight forward.

> Minor Data Comments
> 
>   • 4) How do we decide how much test data it's important to have, and what
>     extra value we get from having more? For example, how much better are the
>     tests because we have these five BAMs instead of just one or two, and these
>     ten VCFs instead of just one or two? (Not a problem to have more, but I
>     want to make sure we're being thoughtful about when to have more files and
>     what each new one adds.)

This actually is a really important comment!  The purpose of the
test data is to support the test cases.  We shouldn't just be
added data because someone might needed it.  The idea is to test
coverage of the API behavior, not a stress tests.  So test data
should be crafted to match the tests.  Reusing data between
tests is nice and often expedient, but not necessary if corner
case data is required.

>   • 5) It would be nice if it were easy to download just the compliance data,
>     without also getting all of the code (not a big deal, since the code’s not
>     big today, but a bit of a nuisance).

Agreed.  It would be good to have them as a separate tar file
when we build releases.

**Comment by jeromekelleher** [comment] 2015-08-14 07:29
As far as I know, the test data was derived from some that we use in the reference server for unit testing. It was not specially crafted to be a dataset for compliance tests, and it's not internally consistent. The reference in particular is completely arbitrary. So, I think this particular set is fine to get us started, but it should be replaced with a properly thought-out dataset which has consistent reads, references and variants. I agree with @diekhans  that we shouldn't require standard references and other data --- unless the data is small and standalone, running these tests in an automated way on something like TravisCI would be hard.

In the reference server, the directory hierarchy maps to the data hierarchy. Each directory in the reads directory is a readgroupset, each directory in a readgroupset is a readgroup, etc. Again, this is internal to the reference server, and not something that was intended to be used more widely. We should change the layout of the test datasets to something that is easy for all implementers to import.

**Comment by sarahhunt** [comment] 2015-08-14 10:03
It's non-trivial for us to support the full test data as it stands due to it's structure. We consider a dataset to be a set of VCFs produced in the same analysis -1KG phase 1 and 1KG phase 3 would be two different datasets. On disk a dataset has a single directory of VCFs, with one file per chromosome.
Dataset is not overly specified in the schema, so this interpretation fitted with pre-existing Ensembl approaches, though I realise it's not how an archive would operate. 
I could add a subset to our public prototype fairly quickly. I've not yet checked which set is most heavily used.

**Comment by dglazer** [comment] 2015-08-14 13:26
**Re my question (1), about mapping BAMs to readgroupsets**

> In the reference server, the directory hierarchy maps to the data hierarchy ... this is internal to the reference server, and not something that was intended to be used more widely. We should change the layout of the test datasets to something that is easy for all implementers to import.

Makes sense @jeromekelleher -- I agree we should set up test data in a way that's easy for everyone to import. (Meaning I don't mind having to do a little shuffling, as long as it's easy and well-defined.) This thread is showing that the three existing servers have three different conventions, so I'm glad we're talking through them.

> Each directory in the reads directory is a readgroupset, each directory in a readgroupset is a readgroup, etc.

I don't follow this convention. The /reads directory in the test data contains the following BAMs:
```
reads/1kg-low-coverage/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
reads/1kg-low-coverage/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
reads/1kg-low-coverage/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
reads/wgBam/wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam
reads/wgBam/wgEncodeUwRepliSeqBg02esG2AlnRep1_sample.bam
```
Per your comment, that would map to two readgroupsets (`1kg-low-coverage` and `wgBam`), and since there are no sub-directories presumably one readgroup each. I would have expected instead for there to be five readgroupsets (one per file, each corresponding to DNA from a different sample), containing as many readgroups as the BAM file tags specifies.

Let's first agree on the intent, and then we can agree on a convention for representing that in the test data.

**Comment by dglazer** [comment] 2015-08-14 13:39
**Re my question (2) about reads matching refs, and (4) about selection of test data**
Sounds like we all agree this isn't an ideal carefully designed test dataset, but it's probably sufficient to get started, and can be enhanced over time.

**Re my question (3) about std vs. custom references**
Good point @diekhans about model organism data. I also expect some servers won't have any easy ability to import new references, since they'll just hardwire the ones they need. For the tests, that probably means (eventually) having one 'module' that tests custom references, and possibly one 'module' that checks for existence of some well-known std references, with test results that make it easy to see per-module test results for a given server.

**Re my question (5) about downloading just the test data**
Sounds like we all agree that would be nice, but isn't blocking a first submit.

**Comment by dglazer** [comment] 2015-08-14 13:48
**Re how the varants/ are laid out**
@sarahhunt 's question made me realize I made some assumptions here that probably aren't right. As with reads, the test data needs to be clear about how it's meant to map to variantsets. The /variants directory contains the following VCFs:
```
variants/1kgPhase1/{chr1,chr2,chr3}.vcf.gz
variants/1kgPhase3/{chr1,chr2,chr3}.vcf.gz
variants/example_1/example_1.vcf.gz
variants/example_2/example_2.vcf.gz
variants/example_3/example_3.vcf.gz
variants/example_4/example_4.vcf.gz
```
How many varianstsets is that expected to yield? Depending on the answer, that might make it hard for  all servers to support, and we might want to come up with tests that only depend on simpler data.

**Comment by jeromekelleher** [comment] 2015-08-14 14:07
@dglazer: a number of points here:

**ReadGroupSets**

Hmmm, you're probably right about the ReadGroupSet->ReadGroup. We had been working on the assumption that 1 readGroup is equivalent to 1 BAM file. So, in reality one BAM file is one ReadGroupSet? 

**References**

 I don't understand this point:
>  I also expect some servers won't have any easy ability to import new references, since they'll just hardwire the ones they need. 

Surely the server must have the reference data on hand in some way, if it's going to be able to respond to (say) ``ListReferenceBases`` queries? If the server stores standard references, then surely it can also store non-standard references? I think it's a bad idea having tests written against 'standard' references. These will change over time, and it means that a server must have gigabytes of data stored to be able to run the compliance suite. I would argue strongly for the test data being complete and self-contained for all tests.

**VariantSets**
That would be 2 VariantSets in the reference server's world. We have a purely hierarchical view of the data, mapping exactly to the layout of files in the file system. A dataset contains some variantSets, and a variantSet consists of one or more, consistent, non-overlapping VCF files. Similarly for ReadGroupSets above (although, we've currently probably got the wrong interpretation of ReadGroup as discussed above). 

In this case, I would throw away one of the variant sets for now.

As you say, we all clearly have different ideas about what the data hierarchy actually means. I would like to formally define it as a hierarchy, as discussed in ga4gh/schemas#248. In any case, it's great that we're actually starting to hash this stuff out: yay for compliance tests!

**Comment by sarahhunt** [comment] 2015-08-14 14:17
That's interesting! I expected you to say 10 VariantSets due to the 
comment in variants.avdl ' The variant set is equivalent to a VCF file.'

Does this mean the example* directories aren't used? Throwing away one 
of the VariantSets for now would get us moving quickly.

**Comment by jeromekelleher** [comment] 2015-08-14 14:29
That's true @sarahhunt, but I think the intention was that related variants that happen to have been split into several files should be one VariantSet. The documentation is unclear though (as is the documentation for reads). I would suggest the following:

- 1 VCF file containing the first 100 variants from chr1, 2 and 3 in 1kg phase 3 for (say) three samples. This is our test VariantSet.
- SAM files for each of these samples, subsetted to contain reads from only the regions covered by the variants.
- A FASTA file containing the sequence for GRCh38 over the regions in question. This should be quite small, and managable. This is our referenceSet.

What do you think; is this a good test set @dglazer and @sarahhunt? Would it be easy enough to import into your systems?

**Comment by lh3** [comment] 2015-08-14 14:29
One read group typically corresponds to one lane. For old data, one BAM usually contains multiple read groups. For typical resequencing, we use one BAM for one sample, though there are exceptions at times. A readgroupset usually corresponds to one BAM.

As @sarahhunt said, one VariantSet is meant to represent one VCF across the whole genome. Nonetheless, we frequently split VCF by chromosomes.

**Comment by sarahhunt** [comment] 2015-08-14 14:35
Yes - that would work for our system. A VariantSet of 3 files in one 
directory would also work if that's easier.

**Comment by diekhans** [comment] 2015-08-14 14:42
Added "Variant data model should be conceptual, not define in terms of VCF file format."
https://github.com/ga4gh/schemas/issues/379

**Comment by diekhans** [comment] 2015-08-14 15:09
in reality, a readgroup can be one or more BAMs.  See

   https://github.com/ga4gh/server/issues/574#issuecomment-131139478

that describes the situation.

**Comment by lh3** [comment] 2015-08-14 15:32
All combinations happen in practice, but I think we should just implement the common practice (one bam per sample containing one or several read groups) and throw an error in the uncommon cases for now.

**Comment by dglazer** [comment] 2015-08-14 23:31
@jeromekelleher, I agree that:
>  In any case, it's great that we're actually starting to hash this stuff out: yay for compliance tests!

**Re Readgroupsets**
As @lh3 says, there are many possible ways to map between files and readgroupsets, with the most common practice being one BAM == one readgroupset. (FYI, Google's import code supports that practice by default, but also lets you import data with other mappings -- see our [understanding readgroupset assignment](https://cloud.google.com/genomics/v1beta2/managing-reads?hl=en#readgroupsetids) doc for details.)

For the compliance test data, we just need to agree on what we intend and document it. I suggest we go with the common model of one BAM file per desired readgroupset, with reads being assigned to readgroups based on the tags in the file.

**Re References**
 I withdraw my original suggestion, and agree that it makes sense for the tests to include a custom reference. I still think the tests should be modular, so that (e.g.) missing support for custom references doesn't force failures around reads, or missing support for reads doesn't force failures around variants.

**Re Variantsets**
I'll comment later in https://github.com/ga4gh/schemas/issues/379 on the general concepts. For the compliance test data, we again just need to agree on what we intend and document it. I'd be happy with @jeromekelleher 's suggestion of a single variantset:
> 1 VCF file containing the first 100 variants from chr1, 2 and 3 in 1kg phase 3 for (say) three samples. This is our test VariantSet.

**Comment by sarahhunt** [comment] 2015-08-17 12:19
It looks as if the compliance suite searching for specific ids. If this is necessary, can the expected ids be documented in the test-data directory, so we know how to set the compliance dataset up? 

Running :  ./ctk --ctk.tgt.urlRoot=http://localhost:3000/ga4gh

I see messages like:

[TESTLOG] FAILED [5] http://localhost:3000/ga4gh//variantsets/search (checkSearchRouting)(org.ga4gh.cts.api.variants.CallsetsSearchResponseCheckIT) due to
 expected:<40[0]> but was:<40[4]>
[o.g.c.t.a.AvroJson ] stubbing future comms due to problem communicating JSON with http://localhost:3000/ga4gh/callsets/{id} id: 1a666305-0eac-47c2-80de-bb7b3920b628

I expect this to fail, as the server is using v0.5.1 which does not have this get method, but that looks suspiciously like a hardcoded callset id.

**Comment by dglazer** [comment] 2015-08-17 13:10
I don't think compliance tests should use hard-coded ids, since ids are server-generated strings, not user-provided ones. @hjellinek , any thoughts?

**Comment by jeromekelleher** [comment] 2015-08-17 13:21
I agree --- the compliance test shouldn't use hard-coded IDs. I suggest we use the ``name`` field for this. For example, we require that the test dataset should have ``name`` equal to ``compliance_dataset_1``. The tests should then be able to get the ID of this dataset using the ``SearchDatasetRequest``, and move from there. A similar approach will work for the other objects, except for ``VariantSet`` which doesn't have a name (which seems like an omission?).

**Comment by hjellinek** [comment] 2015-08-17 16:49
@dglazer, you are right, some of the tests use hard-coded IDs where, as @jeromekelleher says, we should be using names.  Assuming I understand the distinction:

Let me test my understanding, which is that the tests need some way of asserting that certain known-to-be-present objects are indeed present in the compliance test data set.  That means that it should be possible to have lists of strings in, say, class `TestData`, and pass them to the appropriate server methods to retrieve the objects they denote.  And this should be true for every type of server-borne object.

Do you agree?

Assuming you do, then if we call those `TestData` strings "names" and the server-generated strings that can also denote objects to be "IDs", it's fine with me.  I just want to make sure that every retrievable type of object can be retrieved by what we're calling a name.  (And can we also retrieve them using an ID?  If not, what are IDs for?)

**Comment by diekhans** [comment] 2015-08-17 17:02
I don't think it's documented or decided what ids are.  If I am wrong, please point
me at the doc.

However, given reference server assigns ids, we should probably test with names
for the moment.

EBI, how does Ensembl create GA4GH ids?

**Comment by dglazer** [comment] 2015-08-17 19:52
Sounds like both the reference server and Google are going with the "server assigns ids" model, so yes, let's plan on that for the tests. @jeromekelleher 's suggestion of using `name` fields sounds good to me, at least for most object types; we can deal with any problematic objects as we hit them.

**Comment by sarahhunt** [comment] 2015-08-18 08:30
@diekhans - In Ensembl our internal ids are database sequence derived, but we did not want to expose them externally as they are not necessarily consistent between releases. When we were setting up the API, there were discussions within GA4GH about adopting data derived ids, so we used  placeholders pending the outcome of that discussion. The data set and variant set ids are from simple numeric sequences and the callset and variant ids are the sample/variant names - these are unique within the datasets as we configure them.

**Comment by macieksmuga** [comment] 2015-08-21 17:58
I created a new dataset that hopefully addresses most of the criticism leveled at the present one. It currently only comprises variants, reads and reference relevant to the BRCA1 region, but it can easily be expanded to include one or two more smallish genes-worth of data.

Please find it on my fork of this repository, [here](https://github.com/macieksmuga/compliance/tree/compliance_redux/test-data)
I'd greatly appreciate any feedback you may have before I formulate an official PR against it.

**Comment by dglazer** [comment] 2015-08-21 20:19
Looks good at a quick glance, and a nice simplification of the first
version.

CH, do we have any strong feelings about SAM vs. BAM as the input data? The
README says:

Since the compliance data are provided as human-readable FASTA, SAM and VCF
files, these will likely need to be converted to equivalent optimized and
indexed files when imported into the server being tested.

That seems reasonable in theory; just want to double-check there aren't any
gotchas in practice.

**Comment by calbach** [comment] 2015-08-21 20:22
Sounds reasonable to me for the purposes of human inspection. Conversion to BAM is pretty straightforward/reliable, if needed.

**Comment by macieksmuga** [comment] 2015-08-21 20:25
Thanks @dglazer & @calbach - I'll issue a PR on this presently. Note that the tests will still need to be updated to reflect this new data. 

And feel free to toss in your favorite small gene(s) to add to the dataset.

**Comment by diekhans** [comment] 2015-08-21 20:38
Exactly.  We can provide a mvn target to generate the binary versions and indexs or just leave it to the server implementations.

If thiis is problematic it indicates so me wrong with the data

-- Sent from my computer phone

-----Original Message-----

**Comment by macieksmuga** [comment] 2015-08-21 20:45
@calbach Note that human-readable also means that future changes to the data will result in clean, easy to understand diffs.

**Comment by macieksmuga** [comment] 2015-08-28 19:10
Since a first version of compliance data were generated from suggestions in this thread, I'm now closing the issue. Please create new issues for any specific problems or enhancement requests with the new dataset.

**Closed by macieksmuga** 2015-08-28 19:10 UTC
Labels: in progress
